version: "3"

volumes:
  zeebe_data:
  zeebe_elasticsearch_data:

networks:
  zeebe_network:
    driver: bridge

services:
  zeebe:
    container_name: camunda-zeebe
    image: camunda/zeebe:1.0.0
    environment:
      - ZEEBE_LOG_LEVEL=debug
    ports:
      - "26500:26500"
      - "9600:9600"
      - "5701:5701"
    volumes:
      - ./lib/zeebe-hazelcast-exporter-1.0.0.jar:/usr/local/zeebe/exporters/zeebe-hazelcast-exporter-1.0.0.jar
      - ./application.yaml:/usr/local/zeebe/config/application.yaml
    networks:
      - zeebe_network
      
  zeebe-tasklist:
    container_name: camunda-zeebe-tasklist
    image: camunda/zeebe-simple-tasklist:latest
    environment:
      - zeebe.client.broker.contactPoint=zeebe:26500
      - zeebe.client.worker.hazelcast.connection=zeebe:5701
    ports:
      - "8081:8081"
    depends_on:
      - zeebe
    networks:
      - zeebe_network

  #monitor:
  #  container_name: camunda-zeebe_monitor
  #  restart: always
  #  image: ghcr.io/camunda-community-hub/zeebe-simple-monitor:2.0.0
  #  environment:
  #    - zeebe.client.broker.contactPoint=zeebe:26500
  #    - zeebe.client.worker.hazelcast.connection=zeebe:5701
  #  volumes:
  #    - ./application-zeebe-monitor.yaml:/application.yaml
  #  ports:
  #    - "8082:8082"
  #  depends_on:
  #    - zeebe
  #  networks:
  #    - zeebe_network

  operate:
    container_name: camunda-operate
    image: camunda/operate:1.1.0
    ports:
      - "8083:8080"
    depends_on:
      - zeebe
      - elasticsearch
    volumes:
      - ./lib/application.yml:/usr/local/operate/config/application.yml
    networks:
      - zeebe_network

  elasticsearch:
    container_name: camunda-elasticsearch
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:7.10.2
    ports:
      - "9200:9200"
    environment:
      - discovery.type=single-node
      - cluster.name=elasticsearch
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    volumes:
      - zeebe_elasticsearch_data:/usr/share/elasticsearch/data
    networks:
      - zeebe_network

  kibana:
     container_name: camunda-kibana
     image: docker.elastic.co/kibana/kibana-oss:6.7.1
     environment:
       - elasticsearch.url="http://elasticsearch:9200"
     ports:
       - "5601:5601"
     depends_on:
      - elasticsearch
     networks:
       - zeebe_network
       
  #postgres:
  #      container_name: camunda-postgres
  #      image: postgres:latest
  #      restart: always
  #      environment: 
  #        - POSTGRES_USER=postgres
  #        - POSTGRES_PASSWORD=postgres
  #      logging:
  #        options:
  #          max-size: 10m
  #          max-file: "3"
  #      ports:
  #        - '5432:5432'
