version: "2"

networks:
  zeebe_network:
    driver: bridge

services:
  monitor:
    container_name: zeebe_monitor
    image: ghcr.io/camunda-community-hub/zeebe-simple-monitor:2.0.0
    environment:
      - zeebe.client.broker.contactPoint=zeebe:26500
      - zeebe.client.worker.hazelcast.connection=zeebe:5701
    volumes:
      - ./simple-monitor-application.yaml:/application.yaml
    ports:
      - "8082:8082"
    networks:
      - zeebe_network
